# -*- coding: utf-8 -*-
"""updated_ising_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aDMqRQdA_V0Qkm14HQVsPUfQx0H9PtjJ
"""

import numpy as np
import matplotlib.pylab as plt
import os, json, sys
import time
from tqdm import tqdm
from IPython.display import clear_output

def compute_magnetization(config):
    return np.sum(config) / config.size

def heat_bath(config, beta, c, decay_const, H, K, bias):

    L, M = config.shape
    kL, kM = K.shape
    radL = kL // 2
    radM = kM // 2
    dt = 1.0 / (L * M)           #time step per MC sweep

    for _ in range(L * M):
        i = np.random.randint(L)
        j = np.random.randint(M)

        #nearest-neighbor field
        h = (config[(i + 1) % L, j] +
             config[(i - 1) % L, j] +
             config[i, (j + 1) % M] +
             config[i, (j - 1) % M])

        local_field = h + H[i, j] + bias[i, j]

        pi_plus = 1.0 / (1.0 + np.exp(-2.0 * beta * local_field)) #probability for heat-bath algo

        config[i, j] = 1 if np.random.rand() < pi_plus else -1   #spin update

        #finding rows and columns involved in inhibition
        rows = (i - radL + np.arange(kL)) % L
        cols = (j - radM + np.arange(kM)) % M
        section = config[np.ix_(rows, cols)]

        inhib = np.sum(K * section) / np.sum(K)

        #Update field H
        H[i, j] = H[i, j] - (c * inhib * dt) - (decay_const * H[i, j] * dt)

    return config, H

def monte_carlo(L, M, beta, monte_carlo_move, n_steps, wait_time,
                c, decay_const, H, movie_start, movie_end, K, bias):

    spin_configuration = np.random.choice([-1, 1], size=(L, M)) #initial grid

    magnetizations = np.zeros(n_steps)
    field_H = []
    store_spins = []

    # Equilibration time
    for _ in tqdm(range(wait_time)):
        spin_configuration, H = monte_carlo_move(
            spin_configuration, beta, c, decay_const, H, K, bias
        )
    print('Burn in done!')

    # MC sweeps post burn in
    for t in tqdm(range(n_steps)):
        spin_configuration, H = monte_carlo_move(
            spin_configuration, beta, c, decay_const, H, K, bias
        )

        magnetizations[t] = compute_magnetization(spin_configuration)

        if movie_start <= t < movie_end:
            store_spins.append(spin_configuration.copy())
            field_H.append(H.copy())

    return magnetizations, store_spins, field_H

start_time = time.time()

L, M = 39, 78       #dimensions of the grid (need not be equal anymore)
H0 = np.zeros((L, M))
bias_val = -1.
beta = 0.6  # inverse temp.
c = 4
decay_const = 4
rad = 9  #inhibition range

n_steps = 2000
wait_time = 2000
movie_start=0
movie_end=n_steps

bias = np.ones((L, M)) * bias_val

#constructing the 'diamond' kernel
kernel = np.zeros((2*rad+1, 2*rad+1), dtype=int)
for i in range(rad+1):
    kernel[i, rad-i:(rad+i+1)] = 1
    kernel[-i-1, rad-i:(rad+i+1)] = 1

mag, store_spins, H = monte_carlo(
    L,
    M,
    beta,
    heat_bath,
    n_steps,
    wait_time,
    c,
    decay_const,
    H0,
    movie_start,
    movie_end,
    kernel,
    bias
)

print("--- %s seconds ---" % (time.time() - start_time))

## Showing the spins ##

for idx in range(0, n_steps):

    plt.matshow(store_spins[idx])
    plt.xticks([])
    plt.yticks([])
    plt.title(idx)
    plt.show()
    clear_output(wait=True)

## To export as .mat file for Florian
from scipy.io import savemat

data_to_save = {
        'stored_spins': store_spins
    }
savemat('updated_ising.mat', data_to_save)